# Generated by Django 6.0.2 on 2026-02-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_text_choice_choice_ttext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_TText',
            new_name='choice_text',
        ),
    ]
